### ISSUE TITLE
Feedback on topic: Community safety

### ISSUE THREAD

**Issue by arfon** [github/open-source-survey#11]
As described in the [`README`](https://github.com/github/the-open-source-survey#how-you-can-help), we'd love to hear from you about any existing survey instruments you know of that that explore the survey [topic areas](https://github.com/github/the-open-source-survey/blob/master/survey-topics.md) we're interested in.

Please use this issue to let us know about existing survey instruments and research on _Community safety_:

> Online harassment is widespread problem that has discouraged participation in online spaces, such as those where open source development takes place, by women and other underrepresented groups. While there have been high-profile cases that generated substantial coverage in the press, and our support team is aware of cases that are escalated to GitHub, there has been no representative study of the prevalence, dynamics, and consequences of online harassment in open source.

**Comment by mlinksva** [comment]
http://flosspols.merit.unu.edu/deliverables/D16HTML/FLOSSPOLS-D16-Gender_Integrated_Report_of_Findings.htm (2006) motivated by FLOSS 2002's demographics (1.5% female) apparently surveyed 1541 people, though I can't find any description of the population. Questions included:

- For whom (men or women) is it easier to get acknowledgement for work in the F/LOSS community?
- Regarding the FLOSS community as a whole, have you ever observed discriminatory behaviour against women?
- Regarding your collaboration with others during your FLOSS activities, have you ever observed or experienced discriminatory behaviour against women?
- Have you ever been asked for a date by a F/LOSS participant?
- In online contexts women often get more attention as a woman rather than a F/LOSS participant.
- In offline contexts women often get more attention as a women rather than a F/LOSS participant.

To some of these male and female respondents gave sharply different answers.

**Comment by arfon** [comment]
✨ @mlinksva thanks for finding this. I'm closing [these review issues](https://github.com/github/open-source-survey/milestone/1) now and incorporating this feedback in the next iteration of the design.
