### ISSUE TITLE
Feedback on topic: Relationship to closed source development & the workplace

### ISSUE THREAD

**Issue by arfon** [github/open-source-survey#15]
As described in the [`README`](https://github.com/github/the-open-source-survey#how-you-can-help), we'd love to hear from you about any existing survey instruments you know of that that explore the survey [topic areas](https://github.com/github/the-open-source-survey/blob/master/survey-topics.md) we're interested in.

Please use this issue to let us know about existing survey instruments and research on _Relationship to closed source development & the workplace_:

> Much open source development is subsidized by companies, who either employ engineers to work on open source projects, or allow them to work on those projects when they also provide value to the firm. We’d like to explore how supported developers feel by their employers to contribute to open source i.e. are there IP agreements covering their open source contributions? If so, what do they look like?

> In addition, we’d like to explore what the decision making process look like for companies adopting open source/incorporating an open source dependency in their technology stack.

**Comment by jlipps** [comment]
One of the things that would be interesting to me for a survey like this to cover (especially longitudinally if this survey continues into the coming years) is attitudes towards and motivations for contributing to open source. This topic ("relationship to closed source development and the workplace") gets at some of that (who is contributing because their company told them to or allows them to?) but I wonder if a different or broader topic might be more relevant to the interest I mentioned.

A question along the lines of "What do you get out of contributing to open source?" is an example of what I'm thinking about here; obviously it's very broad. But I think tracking this over time would be really enlightening and help us understand the changing nature of open source contribution and what "open source" even means to people over time.

**Comment by jlipps** [comment]
And apologies that my question isn't strictly about existing instruments; I initially thought the issue was for comment on this topic in general.

**Comment by arfon** [comment]
Many thanks for the feedback here @jlipps. We're going to be incorporating this and the feedback on [other feedback issues](https://github.com/github/open-source-survey/labels/help%20wanted).
