### ISSUE TITLE
Sexual orientation

### ISSUE THREAD

**Issue by CoralineAda** [github/open-source-survey#38]
"Queer" should be added to the lesbian, gay, bisexual question. Although this was a contentious word at one time it is currently recognized and adopted by a significant portion of people who are not straight.

**Comment by vmbrasseur** [comment]
For that matter, it's worth including "asexual."

**Comment by nmsanchez** [comment]
It has been my experience doing D&I trainings outside the U.S. that "queer" doesn't translate well. I use it almost exclusively in place of "LGBT" in the states because that list is so limited and jumbled between gender and sexual orientation. I worry, then, that it will push queer folks outside the U.S. to not participate in the survey if it is present. Would love to hear more from the Octoqueer group. I'll put this conversation in the Slack channel.

**Comment by franniez** [comment]
Thanks for the feedback and discussion. While we see the reasoning for this suggestion, because "queer" is still understood as a slur in some places, and because the audience for this survey is international, we're avoiding using this term here. We've reworded the question on sexual orientation to include asexual and to be more inclusive of a broader range of sexual orientations.
