### ISSUE TITLE
Adding an "Other" answer to the questions about Harassment

### ISSUE THREAD

**Issue by anjuan** [github/open-source-survey#39]
I think the **HARASSMENT-WITNESS** and  **HARASSMENT-EXPERIENCE** sections could benefit from an "Other" answer. For example, harassers can do the following acts to targets that are not clearly included in the current list: ddoss the personal site of another person or the site of their employer, ban from open source projects by revoking privileges, and incite others to (often anonymously) engage in threats and harassment. I think it would be helpful to allow write-in responses instead of prescribing the range of likely answers.

**Comment by franniez** [comment]
Thanks for this suggestion. We agree, there should be space to describe forms of harassment or negative experiences that aren't covered by the closed response options. We've added "Other" options with open text boxes to these questions.

We won't be able to release verbatim open text responses associated with other respondent data, due to privacy concerns. We can, however, compile and publish a list of themes and experiences that are uncovered by the open text, to inform future research efforts.

**Comment by anjuan** [comment]
Thank you!
