### ISSUE TITLE
Will the results be published regardless of outcome?

### ISSUE THREAD

**Issue by techzilla** [github/open-source-survey#71]
This is a major concern for me,  I'd hope that the results are publicly published regardless of if they appear as the researches expected.

**Comment by franniez** [comment]
Yes! This is an [open data project](https://github.com/github/open-source-survey#open-data) and we'll be publishing the data under an open source license for the open source community and researchers to use. We may hold back some data if there are [privacy concerns](https://github.com/github/open-source-survey/blob/master/design-principles.md#open-data-and-respondent-privacy), but otherwise we plan to release the full data set with accompanying docs on sampling methodology etc.

**Comment by piercus** [comment]
@franniez can i ask when do you plan to publish the data ? and if you will notify survey participants ?

I just wantto make sure i won't miss it !

**Comment by franniez** [comment]
@piercus Since the survey is totally anonymous, we don't have a way of notifying participants, but you can sign up for updates at opensourcesurvey.org. I think we'll be able to release the data in May, but since we're still in data collection it's hard to predict.
